# Generated by Django 5.2.7 on 2025-10-19 13:38

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_avatar_alter_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.get_avatar_upload_path, verbose_name='Avatar'),
        ),
    ]
