# Generated by Django 5.2.7 on 2025-10-19 13:49

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.get_banner_upload_path, verbose_name='Banner'),
        ),
    ]
