# Generated by Django 5.2.7 on 2025-10-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='media_type',
            field=models.CharField(default='movie', max_length=50),
        ),
    ]
